#!/bin/bash

# Run iRODS iinit for given user. This scripts gets iCAT host and zone
# values from /etc/ireinit.env. Useful for quickly logging into the
# default zone or for changing users in tutorial exercises.
#
# This is a EBRC custom script installed by ebrc-irods Puppet module,
# not part of the iRODS package.


USER=$1

if [ -z "$USER" ]; then
  echo "Usage: iinit.sh <irods_user>"
  exit 1
fi

echo -n "password: "
read -s PASSWD
echo

. /etc/ireinit.env

iexit full

rm -f ~/.irods/irods_environment.json

echo | iinit >/dev/null 2> >(grep -v 'Inappropriate ioctl') <<EOF
$ICAT_SERVER_HOST
$ICAT_SERVER_PORT
$1
$ICAT_SERVER_ZONE
$PASSWD
EOF

