#!/bin/bash

# Run iRODS iinit for given user. This script gets iCAT host and zone
# values from /etc/ireinit.env. Useful for quickly logging into the
# default zone or for changing users in tutorial exercises.
#
# This is a EBRC custom script installed by ebrc-irods Puppet module,
# not part of the iRODS package.

this=`basename $0`

USER=$1

if [ -z "$USER" ]; then
  echo "Usage: ${this} <irods_user>"
  exit 1
fi

echo -n "password: "
read -s PASSWD
echo

. /etc/ireinit.env

iexit full

rm -f ~/.irods/irods_environment.json

echo | iinit >/dev/null 2> >(grep -v 'Inappropriate ioctl') <<EOF
$PROVIDER_SERVER_HOST
$PROVIDER_SERVER_PORT
$1
$PROVIDER_SERVER_ZONE
$PASSWD
EOF

